FROM python:3.10

WORKDIR /app

# Copy necessary files
COPY bot/bot.py /app/bot.py
COPY bot/chatgpt.py /app/chatgpt.py
COPY bot/database.py /app/database.py
COPY requirements.txt /app/requirements.txt  

# Install dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Run the bot
CMD ["python", "/app/bot.py"]
